
export const FETCH_TRACKS_REQUEST = 'FETCH_TRACKS_REQUEST';
export const FETCH_TRACKS_FAIL = 'FETCH_TRACKS_FAIL';
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';

export const CLICK_ACTIVE_TRACK = 'CLICK_ACTIVE_TRACK';
export const SET_TRACK_ACTIVE = 'SET_TRACK_ACTIVE';

export const CLICK_NEXT_TRACK = 'CLICK_NEXT_TRACK';
export const SELECT_NEXT_TRACK = 'SELECT_NEXT_TRACK';

export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';

export const TOGGLE_PLAY = 'TOGGLE_PLAY';